'Un equipo de voleyball tiene de 6 a 20 jugadores, 
'uno de los cuales es el capitán del equipo. 
'Todo equipo tiene un nombre y un registro, 
'y todo jugador tiene un número y una posición. 
'Los equipos compiten en juegos y cada juego 
'tiene una localidad y una puntuación. 
'Un equipo puede tener un entrenador que 
'tiene un nivel de acreditación y un 
'número de años de experiencia. 
'Un mismo entrenador puede entrenar 
'diferentes equipos. Cualquier persona, 
'ya sea jugador de un equipo, 
'así como el entrenador, tienen 
'un teléfono, nombre y dirección.

@startuml DiagramaDeClases

class Equipo{
    -nombre: String
    -registro: String
    -capitan: jugadores
}
class Persona{
    -telefono: Int
    -nombre: String
    -direccion: String
}
class Entrenador{
    -nivelAcreditacion: Int
    -anosDeExperiencia: Int
}
class Jugadores{
    -numero: Int
    -posicion: String
}
class Juego{
    -localidad: String
    -puntuacion: String
}

Equipo *-- "6 .. 20" Jugadores
Equipo "2" -- "1" Juego : compiten
Equipo "1 .. *" -- "1" Entrenador : tiene
Persona <|-- Jugadores
Persona <|-- Entrenador

@enduml